# 基本配置
title: tyuecode's blog
description: This is an ordinary blog
baseurl: ""  # 如果部署在子路径，填写子路径
url: "https://tyuecode.github.io"

# 作者信息
author:
  name: tyue
  email: 1252107428@qq.com
  github: tyuecode

# 主题设置（根据主题不同而异）
theme: minima  # 或你的主题名称

# 插件
#plugins:
 # - jekyll-feed
  #- jekyll-seo-tag

# 评论系统（可选）
# 推荐：Gitalk, Utterances, Disqus
#comments:
#  provider: utterances
 # utterances:
  #  repo: 你的用户名/你的用户名.github.io